name: Cache Demo

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cache-demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create cache directory
      run: mkdir -p ./cache-dir
      
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: ./cache-dir
        key: cache-c276e9c-${{ runner.os }}-v1
        restore-keys: |
          cache-c276e9c-${{ runner.os }}-
          
    - name: Populate cache on miss
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        echo "This is cached data - $(date)" > ./cache-dir/cached-file.txt
        echo "Cache populated with timestamp: $(date)"
        
    - name: prime-cache-c276e9c
      run: |
        echo "=== Cache Status Report ==="
        if [ "${{ steps.cache-deps.outputs.cache-hit }}" == "true" ]; then
          echo "RESULT: Cache hit"
          echo "Cached content:"
          cat ./cache-dir/cached-file.txt || echo "No cached file found"
        else
          echo "RESULT: Cache miss" 
          echo "Cache has been primed for next run"
        fi
        echo "Cache key: cache-c276e9c"
        echo "==========================="
        
    - name: Verify cache step succeeded
      run: echo "Cache step completed successfully with key: cache-c276e9c"
